// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwekdhtinhajmchwwpoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3ZWtkaHRpbmhham1jaHd3cG9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTU5ODYsImV4cCI6MjA2OTk3MTk4Nn0.Oy2MpBzf3J-_b7Stm-ePpsdSZmDln1XTHm0DMjw8KLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});